### ISSUE TITLE
panic: Unknown command: rom

### ISSUE THREAD

**Issue by Ashgar** [grammarly/rocker#194]
Hi there 
on Mac, I have go version go1.9.3 darwin/amd64 and try to run ` rocker build .` and I have such output:
``` 
panic: Unknown command: rom

goroutine 1 [running]:
github.com/grammarly/rocker/src/build.NewCommand(0xc420016127, 0x3, 0xc420040670, 0x1, 0x1, 0x0, 0xc420010ba0, 0xc4200160a0, 0xe, 0x0, ...)
	/private/tmp/rocker-20180204-11816-kh978d/build/src/github.com/grammarly/rocker/src/build/commands.go:121 +0x1195
github.com/grammarly/rocker/src/build.NewPlan(0xc4201e01e0, 0x2, 0x2, 0x1, 0x18b5a58, 0x0, 0x0, 0x185c4c0, 0xc42008a000)
	/private/tmp/rocker-20180204-11816-kh978d/build/src/github.com/grammarly/rocker/src/build/plan.go:49 +0x1af
main.buildCommand(0xc4201a60e0)
	/private/tmp/rocker-20180204-11816-kh978d/build/src/github.com/grammarly/rocker/main.go:394 +0x1104
github.com/grammarly/rocker/vendor/github.com/codegangsta/cli.Command.Run(0x159fca2, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x15b3334, 0x2d, 0x0, ...)
	/private/tmp/rocker-20180204-11816-kh978d/build/src/github.com/grammarly/rocker/vendor/github.com/codegangsta/cli/command.go:117 +0x521
github.com/grammarly/rocker/vendor/github.com/codegangsta/cli.(*App).Run(0xc420164000, 0xc42007a090, 0x3, 0x3, 0x0, 0x0)
	/private/tmp/rocker-20180204-11816-kh978d/build/src/github.com/grammarly/rocker/vendor/github.com/codegangsta/cli/app.go:159 +0x529
main.main()
	/private/tmp/rocker-20180204-11816-kh978d/build/src/github.com/grammarly/rocker/main.go:233 +0x1b70 
```

Rockerfile is:
```
ROM python:3.6

RUN echo "hello" > t.txt
```

Any idea why I might have this? thank you in advance.

**Comment by ybogdanov** [comment]
Thanks for reporting. Unfortunately, we are discontinuing this project. See the notice here: https://github.com/grammarly/rocker/blob/master/README.md

Closing this issue as we are not able to address it. Sorry.
