### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ionelmc** [grammarly/rocker#92]
I'm using the 1.1.2 linux release on ubuntu 14.04 and I get this:

```
ionel:newbox ~/sandbox/rocker/example master> rocker build /.                                                                                                                                    0.00s => 0 15:58
INFO[0000] FROM google/golang:1.4
INFO[0004] | Pull image google/golang:1.4
1.4: Pulling from google/golang
a3ed95caeb02: Pull complete
dc50bc165b2f: Pull complete
a2d87a290ee1: Pull complete
90b9f6f49946: Pull complete
30b3e209d8f2: Pull complete
Digest: sha256:86e7abc3972bc8c7e353c5b1d57dbf367b55ee28830c5f3543f4f101b9f16e83
Status: Downloaded newer image for google/golang:1.4
INFO[0053] | Image sha256:85b3e                          size=624.8 MB
INFO[0053] ADD . /src
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x4b78ea]

goroutine 1 [running]:
github.com/grammarly/rocker/src/build.listFiles.func1(0xc820261380, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/grammarly/rocker/src/build/copy.go:317 +0x1ba
path/filepath.walk(0xc8202611a0, 0xe, 0x7fdef25dac58, 0xc82e9c4fa0, 0xc8205c3160, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:370 +0x415
path/filepath.walk(0xc820260ba0, 0xb, 0x7fdef25dac58, 0xc82e9c4910, 0xc8205c3160, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:374 +0x4fc
path/filepath.walk(0xc82db5bec0, 0x5, 0x7fdef25dac58, 0xc82db8aa00, 0xc8205c3160, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:374 +0x4fc
path/filepath.walk(0xc8202f7bd0, 0x1, 0x7fdef25dac58, 0xc82033cff0, 0xc8205c3160, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:374 +0x4fc
path/filepath.Walk(0xc8202f7bd0, 0x1, 0xc8205c3160, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:396 +0xe1
github.com/grammarly/rocker/src/build.listFiles(0x7ffcd4be8ad6, 0x2, 0xc82016f380, 0x1, 0x2, 0xfffd28, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/grammarly/rocker/src/build/copy.go:355 +0x5ef
github.com/grammarly/rocker/src/build.makeTarStream(0x7ffcd4be8ad6, 0x2, 0xc8202f7a40, 0x4, 0xa9d4d8, 0x3, 0xc82016f380, 0x1, 0x2, 0xfffd28, ...)
        /go/src/github.com/grammarly/rocker/src/build/copy.go:149 +0x184
github.com/grammarly/rocker/src/build.copyFiles(0xc8200e6b00, 0xc82016f380, 0x2, 0x2, 0xa9d4d8, 0x3, 0xc8202f7730, 0xc, 0x0, 0x0, ...)
        /go/src/github.com/grammarly/rocker/src/build/copy.go:84 +0x73f
github.com/grammarly/rocker/src/build.(*CommandAdd).Execute(0xc820017900, 0xc8200e6b00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/grammarly/rocker/src/build/commands.go:1072 +0x119
github.com/grammarly/rocker/src/build.(*Build).Run(0xc8200e6b00, 0xc820141800, 0x11, 0x20, 0x0, 0x0)
        /go/src/github.com/grammarly/rocker/src/build/build.go:116 +0x68a
main.buildCommand(0xc8200b6620)
        /go/src/github.com/grammarly/rocker/main.go:374 +0x233c
github.com/grammarly/rocker/vendor/github.com/codegangsta/cli.(*App).RunAsSubcommand(0xc8200a1000, 0xc8200b6540, 0x0, 0x0)
        /go/src/github.com/grammarly/rocker/vendor/github.com/codegangsta/cli/app.go:262 +0xe03
github.com/grammarly/rocker/vendor/github.com/codegangsta/cli.Command.startApp(0xaa01b8, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0xb5c8c0, 0x2d, 0x0, ...)
        /go/src/github.com/grammarly/rocker/vendor/github.com/codegangsta/cli/command.go:182 +0x4e5
github.com/grammarly/rocker/vendor/github.com/codegangsta/cli.Command.Run(0xaa01b8, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0xb5c8c0, 0x2d, 0x0, ...)
        /go/src/github.com/grammarly/rocker/vendor/github.com/codegangsta/cli/command.go:45 +0x15ee
github.com/grammarly/rocker/vendor/github.com/codegangsta/cli.(*App).Run(0xc8200a0f00, 0xc82000a240, 0x3, 0x3, 0x0, 0x0)
        /go/src/github.com/grammarly/rocker/vendor/github.com/codegangsta/cli/app.go:159 +0xc2f
main.main()
        /go/src/github.com/grammarly/rocker/main.go:214 +0x25cd

goroutine 17 [syscall, 1 minutes, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall, 1 minutes]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 6 [select, 1 minutes, locked to thread]:
runtime.gopark(0xbbe898, 0xc82002c728, 0xaa29f0, 0x6, 0x435818, 0x2)
        /usr/local/go/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc82002c728, 0x0, 0x18)
        /usr/local/go/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc82002c728)
        /usr/local/go/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
        /usr/local/go/src/runtime/signal1_unix.go:227 +0x353
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 7 [chan receive, 1 minutes]:
github.com/grammarly/rocker/src/debugtrap.SetupDumpStackTrap.func1(0xc82001cfc0)
        /go/src/github.com/grammarly/rocker/src/debugtrap/debugtrap_unix.go:19 +0x4d
created by github.com/grammarly/rocker/src/debugtrap.SetupDumpStackTrap
        /go/src/github.com/grammarly/rocker/src/debugtrap/debugtrap_unix.go:22 +0x12a

goroutine 23 [select, 1 minutes]:
net/http.(*persistConn).writeLoop(0xc8201fc000)
        /usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:686 +0xc9d

goroutine 22 [select, 1 minutes]:
net/http.(*persistConn).readLoop(0xc8201fc000)
        /usr/local/go/src/net/http/transport.go:976 +0xac7
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 34 [IO wait, 1 minutes]:
net.runtime_pollWait(0x7fdef25dc448, 0x72, 0xc82000e1b0)
        /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8204d0a70, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8204d0a70, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8204d0a10, 0xc820518000, 0x800, 0x800, 0x0, 0x7fdef25d6050, 0xc82000e1b0)
        /usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc82002e1a8, 0xc820518000, 0x800, 0x800, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc82025e1b0, 0x7fdef25dc758, 0xc82002e1a8, 0x5, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(*Conn).readRecord(0xc8200dd080, 0xbbea17, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:540 +0x2d1
crypto/tls.(*Conn).Read(0xc8200dd080, 0xc82050e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:901 +0x167
net/http.noteEOFReader.Read(0x7fdef0791de8, 0xc8200dd080, 0xc8200da3c8, 0xc82050e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc82016fc80, 0xc82050e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        <autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc820182780)
        /usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc820182780, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8200da370)
        /usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 35 [select, 1 minutes]:
net/http.(*persistConn).writeLoop(0xc8200da370)
        /usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:686 +0xc9d

goroutine 25 [IO wait, 1 minutes]:
net.runtime_pollWait(0x7fdef25dc208, 0x72, 0xc82000e1b0)
        /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8204d1250, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8204d1250, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8204d11f0, 0xc820473c00, 0x400, 0x400, 0x0, 0x7fdef25d6050, 0xc82000e1b0)
        /usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8201ba0c8, 0xc820473c00, 0x400, 0x400, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc8204feae0, 0x7fdef25dc758, 0xc8201ba0c8, 0x5, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(*Conn).readRecord(0xc8204d82c0, 0xbbea17, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:540 +0x2d1
crypto/tls.(*Conn).Read(0xc8204d82c0, 0xc8204f3000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:901 +0x167
net/http.noteEOFReader.Read(0x7fdef0791de8, 0xc8204d82c0, 0xc820536058, 0xc8204f3000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc820564f20, 0xc8204f3000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        <autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc82056e420)
        /usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc82056e420, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc820536000)
        /usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 26 [select, 1 minutes]:
net/http.(*persistConn).writeLoop(0xc820536000)
        /usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:686 +0xc9d

```

**Comment by diunko** [comment]
Okay, this one was really obvious: https://github.com/grammarly/rocker/commit/98fe4ac025bb4370c7265183a81ecf0ca0bfa2f8

Since you tried `/` as a workdir, possible error could be `access denied` or something like this.

Will release hotfix sometime soon. Try building from dev branch for now.
